# 基础锚点
url:  &url  "http://connectivitycheck.platform.hicloud.com/generate_204"   # 健康检查 URL
blk:  &blk '^(?!.*(?i:(回国|校园|网站|地址|剩余|过期|时间|有效|网址|禁止|邮箱|发布|客服|订阅|节点|群|邀请|返利|循环|获取|流量|到期|下次|版本|官址|备用|已用|联系|工单|贩卖|通知|倒卖|国内|频道|说明|提示|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|\d{4}-\d{2}-\d{2}|\d+G))).*$'
prov: &prov {type: http, interval: 86400, health-check: {enable: true, url: *url, interval: 300}}


# ======================= 建议仅修改此部分内容======================
# ========================= 订阅 Providers =======================
# "替换订阅链接"里填入你的机场订阅链接
# [显示名称可修改]即客户端中可显示的节点前缀，可根据喜好自行更改，如：[🐂🍺] -香港节点1 #需保留括号

proxy-providers:
# 机场订阅1
  Node-1:
    <<: *prov
    url: "替换订阅链接1"
    path: './proxy_provider/providers-1.yaml'
    override: {additional-prefix: "[显示名称A可修改] "}
    filter: *blk
# 机场订阅2
  Node-2:
    <<: *prov
    url: "替换订阅链接2"
    path: './proxy_provider/providers-2.yaml'
    override: {additional-prefix: "[显示名称B可修改] "}
    filter: *blk

# ======================  ⬆️⬆️⬆️⬆️⬆️  ========================


# ======================= 以下内容建议小白勿修改 =======================
# ========================== 基础配置 ==========================
mixed-port: 7897
allow-lan: true
bind-address: '*'
mode: rule
log-level: warning
unified-delay: true
tcp-concurrent: true
find-process-mode: strict
global-client-fingerprint: chrome

external-controller: 127.0.0.1:9090
# external-ui: ui
# secret: "yourpassword"

keep-alive-idle: 600
keep-alive-interval: 60

skip-auth-prefixes:
  - 127.0.0.0/8
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 100.64.0.0/10
  - ::1/128
  - fc00::/7
  - fe80::/10

profile:
  store-selected: true
  store-fake-ip: true


# ============================ DNS ============================
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true

  # 国际（加密防污染）
  nameserver:
    - "tls://1.1.1.1"
    - "tls://8.8.8.8"
    - "tls://[2606:4700:4700::1111]"
    - "tls://[2001:4860:4860::8888]"

  # 国内（就近稳定）
  default-nameserver:
    - "223.5.5.5"
    - "119.29.29.29"
    - "180.184.1.1"
    - "[2400:3200::1]"
    - "[2402:4e00::]"

  # 按地域分流解析
  nameserver-policy:
    'geosite:cn':
      - "223.5.5.5"
      - "119.29.29.29"
      - "180.184.1.1"
      - "[2400:3200::1]"
      - "[2402:4e00::]"
    'geosite:geolocation-!cn':
      - "tls://1.1.1.1"
      - "tls://8.8.8.8"
      - "tls://[2606:4700:4700::1111]"
      - "tls://[2001:4860:4860::8888]"

  # 节点域名解析
  proxy-server-nameserver:
    - "system"
    - "tls://1.1.1.1"
    - "tls://8.8.8.8"
    - "tls://[2606:4700:4700::1111]"
    - "tls://[2001:4860:4860::8888]"

  # fake-ip （ruleset 引用 + 仍可追加零星域名）
  fake-ip-filter:
    - rule-set:fake_ip   #  规则集引用
    # 也可继续追加：
    # - 'example.local'


# ========================== 嗅探设置 ==========================
sniffer:
  enable: true
  sniff:
    HTTP: {ports: [80, 8080-8880], override-destination: true}
    TLS:  {ports: [443, 8443]}
    QUIC: {ports: [443, 8443]}
  skip-domain:
    - rule-set:sniff_skip   #  规则集引用
    # 也可继续追加：
    # - "+.example.com"


# ============================ TUN ============================
tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
  strict-route: true
  mtu: 1500


# ========================== Geodata ==========================
geodata-mode: true
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip:   "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb:    "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
  asn:     "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb"


# ============================ 锚点 ============================
# —— 基础模板 —— #
tmpl: &tmpl {url: *url, interval: 300, lazy: true, timeout: 2000, disable-udp: false, max-failed-times: 3, hidden: true, include-all: true}
sel:  &sel  {type: select, url: *url, disable-udp: false, hidden: false, include-all: true}
test: &test {type: url-test, <<: *tmpl, tolerance: 50}
fall: &fall {type: fallback, <<: *tmpl}

# —— 入口 / 应用模板 —— #
entr: &entr {type: select, proxies: ["♻️ 智能选择","👆 手动选择","DIRECT"]}
app:  &app  {type: select, proxies: ["♻️ 智能选择","👆 手动选择","DIRECT","🇭🇰 - 择优节点","🇹🇼 - 择优节点","🇯🇵 - 择优节点","🇰🇷 - 择优节点","🇸🇬 - 择优节点","🇺🇸 - 择优节点","🇬🇧 - 择优节点","🇫🇷 - 择优节点","🇩🇪 - 择优节点"]}
drc:  &drc  {type: select, proxies: ["DIRECT","♻️ 智能选择","👆 手动选择","🇭🇰 - 择优节点","🇹🇼 - 择优节点","🇯🇵 - 择优节点","🇰🇷 - 择优节点","🇸🇬 - 择优节点","🇺🇸 - 择优节点","🇬🇧 - 择优节点","🇫🇷 - 择优节点","🇩🇪 - 择优节点"]}
strm: &strm {type: select, proxies: ["♻️ 智能选择","👆 手动选择","DIRECT","🇭🇰 - 择优节点","🇹🇼 - 择优节点","🇯🇵 - 择优节点","🇰🇷 - 择优节点","🇸🇬 - 择优节点","🇺🇸 - 择优节点","🇬🇧 - 择优节点","🇫🇷 - 择优节点","🇩🇪 - 择优节点","🇭🇰 - 自动回退","🇹🇼 - 自动回退","🇯🇵 - 自动回退","🇰🇷 - 自动回退","🇸🇬 - 自动回退","🇺🇸 - 自动回退","🇬🇧 - 自动回退","🇫🇷 - 自动回退","🇩🇪 - 自动回退"]}

# —— 手动选择（在 sel 基类上加过滤） —— #
manu: &manu {<<: *sel, filter: *blk}

# —— 地区筛选 —— #
hk: &hk '(?i)(🇭🇰|香港|HK|Hong)'
tw: &tw '(?i)(🇹🇼|台湾|TW|Tai|Taiwan)'
jp: &jp '(?i)(🇯🇵|日本|JP|Japan|东京|大阪|埼玉|泉日|川日)'
kr: &kr '(?i)(🇰🇷|韩国|KR|Korea|首尔|韓)'
sg: &sg '(?i)(🇸🇬|新加坡|SG|Singapore|狮)'
us: &us '(?i)(🇺🇸|美国|US|United States|洛杉矶|硅谷|圣何塞|圣克拉拉|西雅图|芝加哥|拉斯维加斯|凤凰城|波特兰|达拉斯|俄勒冈|费利蒙)'
uk: &uk '(?i)(🇬🇧|英国|UK|United Kingdom|伦敦)'
fr: &fr '(?i)(🇫🇷|法国|FR|France)'
de: &de '(?i)(🇩🇪|德国|DE|Germany)'


# ========================= proxy-groups =========================
proxy-groups:
  # 入口与基础
  - {name: "🚀 节点选择", <<: *entr, icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/choice.png"}
  - {name: "👆 手动选择", <<: *manu, icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/select.png"}
  - {name: "♻️ 智能选择", type: url-test, proxies: ["🇭🇰 - 择优节点","🇹🇼 - 择优节点","🇯🇵 - 择优节点","🇸🇬 - 择优节点"], url: *url, interval: 300, tolerance: 50, icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/auto.png"}

  # 应用分组
  - {name: "🌐 全球直连", <<: *drc,  icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/link.png"}
  - {name: "🤖 AI  平台", <<: *app,  icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/openai.png"}
  - {name: "☁️ Onedrive", <<: *app,  icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/onedrive.png"}
  - {name: "Ⓜ️ 微软服务", <<: *app,  icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/microsoft.png"}
  - {name: "🍎 苹果服务", <<: *app,  icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/apple.png"}
  - {name: "🎮 游戏平台", <<: *app,  icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/game.png"}
  - {name: "🎵 Spotify", <<: *strm, icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/spotify.png"} 
  - {name: "📺 视频媒体", <<: *strm, icon: "https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/icons/netflix.png"}

  # 自动优选（地区）
  - {name: "🇭🇰 - 择优节点", <<: *test, filter: *hk}
  - {name: "🇹🇼 - 择优节点", <<: *test, filter: *tw}
  - {name: "🇯🇵 - 择优节点", <<: *test, filter: *jp}
  - {name: "🇰🇷 - 择优节点", <<: *test, filter: *kr}
  - {name: "🇸🇬 - 择优节点", <<: *test, filter: *sg}
  - {name: "🇺🇸 - 择优节点", <<: *test, filter: *us}
  - {name: "🇬🇧 - 择优节点", <<: *test, filter: *uk}
  - {name: "🇫🇷 - 择优节点", <<: *test, filter: *fr}
  - {name: "🇩🇪 - 择优节点", <<: *test, filter: *de}

  # 自动回退（地区）
  - {name: "🇭🇰 - 自动回退", <<: *fall, filter: *hk}
  - {name: "🇹🇼 - 自动回退", <<: *fall, filter: *tw}
  - {name: "🇯🇵 - 自动回退", <<: *fall, filter: *jp}
  - {name: "🇰🇷 - 自动回退", <<: *fall, filter: *kr}
  - {name: "🇸🇬 - 自动回退", <<: *fall, filter: *sg}
  - {name: "🇺🇸 - 自动回退", <<: *fall, filter: *us}
  - {name: "🇬🇧 - 自动回退", <<: *fall, filter: *uk}
  - {name: "🇫🇷 - 自动回退", <<: *fall, filter: *fr}
  - {name: "🇩🇪 - 自动回退", <<: *fall, filter: *de}


# =========================== 规则集 ===========================
cls: &cls {type: http, behavior: classical, interval: 43200, format: text, proxy: "🚀 节点选择"}
dom: &dom {type: http, behavior: domain,    interval: 43200, format: text, proxy: "🚀 节点选择"}

rule-providers:
  FuckAD:               {<<: *dom, format: yaml, url: https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/rules/yaml/fuckAds.yaml,     path: ./rules/yaml/fuckAds.yaml}
  sniff_skip:           {<<: *dom, url: https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/rules/domainset/sniff-skip.list,           path: ./rules/domainset/sniff-skip.list}
  fake_ip:              {<<: *dom, url: https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/rules/domainset/fake_ip.list,              path: ./rules/domainset/fake_ip.list}
  stream_non_ip:        {<<: *cls, url: https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/rules/non_ip/stream.txt,                   path: ./rules/non_ip/stream.txt}
  stream_ip:            {<<: *cls, url: https://cdn.jsdelivr.net/gh/baiye1997/baiye-mihomo-rules@main/rules/ip/stream.txt,                       path: ./rules/ip/stream.txt}

# =========================== 分流规则 ==========================
rules:
  # 非 IP 类
  - GEOSITE,private,DIRECT
  - RULE-SET,FuckAD,REJECT
  - DOMAIN-SUFFIX,bing.com,DIRECT
  - DOMAIN-SUFFIX,oaiusercontent.com,🤖 AI  平台
  - GEOSITE,onedrive,☁️ Onedrive
  - GEOSITE,category-ai-cn,🌐 全球直连
  - GEOSITE,category-ai-!cn,🤖 AI  平台
  - GEOSITE,category-games@cn,🌐 全球直连
  - GEOSITE,category-games,🎮 游戏平台
  - GEOSITE,google-cn,🌐 全球直连
  - GEOSITE,microsoft@cn,🌐 全球直连
  - GEOSITE,microsoft,Ⓜ️ 微软服务
  - GEOSITE,apple-cn,🌐 全球直连
  - GEOSITE,apple,🍎 苹果服务
  - GEOSITE,category-media-cn,🌐 全球直连
  - GEOSITE,spotify,🎵 Spotify
  - RULE-SET,stream_non_ip,📺 视频媒体
  - GEOSITE,category-ai-cn,🌐 全球直连
  - GEOSITE,cn,DIRECT
  - GEOSITE,geolocation-!cn,🚀 节点选择

  # IP 类
  - GEOIP,private,DIRECT,no-resolve
  - RULE-SET,stream_ip,📺 视频媒体,no-resolve
  - GEOIP,telegram,🚀 节点选择,no-resolve
  - GEOIP,cn,DIRECT,no-resolve

  # 兜底
  - MATCH,🚀 节点选择